"use client";

import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, Building2, Check, ChevronRight, ClipboardList, Coffee, Heart, MapPin, Menu, Phone, Search, SlidersHorizontal, Sparkles, Store, Utensils, Scissors, CircleHelp, Mail, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { InquiryForm, type InquiryContext } from "@/components/inquiry-form";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import scenarios from "@/lib/scenarios.json";
import works from "@/lib/real-cases.json";

const money = (n: number) => n.toLocaleString("ko-KR");
const clean = (s: string) => s.replace(/<br\s*\/?\s*>/gi, " ");
const listingMeta: Record<string, {title:string; industry:string; floor:string; area:number; sub:string; tags:string[]}> = {
  cafe: {title:"첫 창업에 맞춘 소형 카페 자리", industry:"카페", floor:"1층", area:13, sub:"생활동선형 · 테이크아웃 추천", tags:["소형 점포", "권리금 없음"]},
  beauty: {title:"단골이 찾아오기 좋은 예약형 숍", industry:"뷰티·서비스", floor:"2층", area:20, sub:"예약형 매장 · 월 부담 비교", tags:["엘리베이터 가정", "이전 검토"]},
  landlord: {title:"기존 시설을 살펴볼 음식점 자리", industry:"음식점", floor:"1층", area:28, sub:"기존 음식점 공실 · 시설 확인 필요", tags:["시설 활용 검토", "권리금 없음"]},
  sale: {title:"임대 현황부터 확인하는 구분상가", industry:"상가 매매", floor:"층수 미설정", area:22, sub:"임대 중인 상가 · 자료부터 비교", tags:["임대 현황 검토", "상가 매매"]}
};
const industries = [{label:"전체", icon:Store}, {label:"카페",icon:Coffee}, {label:"음식점",icon:Utensils}, {label:"뷰티·서비스",icon:Scissors}, {label:"상가 매매",icon:Building2}];
const asset = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH || ""}${path}`;
const tel = "010-6428-8020";
const steps = [
  ["조건 정리", "업종, 초기 예산, 월 부담과 필요한 시설을 함께 정합니다.", "조건 정리표"],
  ["후보 비교", "비용·동선·시설을 같은 기준으로 놓고 장점과 제약을 비교합니다.", "후보 비교표"],
  ["현장 확인", "시설 상태와 시간대별 동선을 현장과 자료로 확인합니다.", "현장 확인 목록"],
  ["협의와 입점", "공사 일정, 시설 인수, 비용 부담을 조율하고 입점까지 살핍니다.", "협의 사항 정리표"]
];

export default function EstateApp() {
  const [route,setRoute] = useState("home");
  const [category,setCategory] = useState("전체");
  const [leaseOnly,setLeaseOnly] = useState(false);
  const [query,setQuery] = useState("");
  const [submittedQuery,setSubmittedQuery] = useState("");
  const [maxRent,setMaxRent] = useState("all");
  const [favorites,setFavorites] = useState<string[]>([]);
  const [recent,setRecent] = useState<string[]>([]);
  const [contact,setContact] = useState(false);
  const [contactGoal,setContactGoal] = useState("상가 임대차 후보 비교");
  const [draft,setDraft] = useState("");
  const [copied,setCopied] = useState(false);
  const [showSaved,setShowSaved] = useState(false);
  const [guide,setGuide] = useState<string|null>(null);
  const [budget,setBudget] = useState(5000);
  const [photoIndex,setPhotoIndex] = useState(0);
  const [mobileMenu,setMobileMenu] = useState(false);
  useEffect(()=>{
    const update = () => {const next = window.location.hash.slice(1)||"home"; setRoute(next); setPhotoIndex(0); setMobileMenu(false); window.scrollTo({top:0}); if(next.startsWith("case/")){const id=next.split("/")[1];setRecent(prev=>[id,...prev.filter(x=>x!==id)].slice(0,3));}};
    update(); window.addEventListener("hashchange",update);
    try {setFavorites(JSON.parse(localStorage.getItem("sun-favorites")||"[]"));} catch { /* Ignore invalid demo preferences. */ }
    return ()=>window.removeEventListener("hashchange",update);
  },[]);
  function toggleFavorite(id:string) {setFavorites(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]; localStorage.setItem("sun-favorites",JSON.stringify(next));return next;});}
  function contactOpen(){setDraft("");setCopied(false);setContactGoal(route==="case/sale"?"상가 매수 검토":"상가 임대차 후보 비교");setContact(true);}
  function selectCategory(label:string){setCategory(label);setLeaseOnly(label==="전체");setMaxRent("all");setShowSaved(false);setSubmittedQuery("");setQuery("");window.location.hash="listings";}
  function search(e:FormEvent){e.preventDefault();setSubmittedQuery(query.trim());setCategory("전체");setLeaseOnly(false);setMaxRent("all");setLeaseOnly(false);setShowSaved(false);window.location.hash="listings";}
  const selected = scenarios.find(s=>route===`case/${s.id}`);
  const work = works.find(w=>route===`work/${w.id}`);
  const inquiryContext: InquiryContext = selected
    ? { kind: "listing", title: listingMeta[selected.id].title, reference: `SUN-00${selected.number}`, goal: selected.price ? "상가 매수 검토" : "상가 임대차 후보 비교" }
    : work ? { kind: "work", title: work.name, goal: contactGoal }
    : { kind: contactGoal === "내 점포 임대 의뢰" ? "landlord" : "general", goal: contactGoal };
  const modalInquiryContext: InquiryContext = contactGoal === "내 점포 임대 의뢰" ? {kind:"landlord",goal:contactGoal} : inquiryContext;
  function previewInquiry(text: string) { setDraft(text); setCopied(false); setContact(true); }
  const filtered = scenarios.filter(s=> (!leaseOnly||!s.price) && (category==="전체"||listingMeta[s.id].industry===category) && (maxRent==="all"||s.rent<=Number(maxRent)) && (!showSaved||favorites.includes(s.id)) && (!submittedQuery||`${listingMeta[s.id].title} ${listingMeta[s.id].industry} ${s.name} ${s.location}`.includes(submittedQuery)));
  const card = (s: typeof scenarios[number]) => <article className="listing-card" key={s.id}>
    <div className="card-photo"><a href={`#case/${s.id}`}><img src={asset(`/images/${s.id}-korea.png`)} alt={`${listingMeta[s.id].industry} 가상 점포 이미지`} loading="lazy"/><span className="photo-label">AI 이미지 · 가상 매물</span></a><button className={`save-button ${favorites.includes(s.id)?"saved":""}`} aria-label={`${listingMeta[s.id].title} ${favorites.includes(s.id)?"찜 해제":"찜하기"}`} onClick={()=>toggleFavorite(s.id)}><Heart size={18} fill={favorites.includes(s.id)?"currentColor":"none"}/></button></div>
    <a href={`#case/${s.id}`} className="card-body"><div className="card-location"><span>산본 중심상가</span><span>{listingMeta[s.id].floor} · {listingMeta[s.id].area}평</span></div><h3>{listingMeta[s.id].title}</h3><div className="card-price"><small>{s.price?"매매":"보증금 / 월세"}</small><strong>{s.price?`${money(s.price)}만원`:<>{money(s.deposit)} <span>/</span> {money(s.rent)}<em>만원</em></>}</strong></div><p>{listingMeta[s.id].sub}</p><div className="tag-row">{listingMeta[s.id].tags.map(t=><span key={t}>{t}</span>)}</div></a>
  </article>;
  const contactCard = <div className="contact-card"><div className="contact-heading"><span className="brand-avatar">선</span><div><small>산본 상가를 가장 가까이에서</small><strong>김영선 <span>공인중개사</span></strong></div></div><a className="contact-phone" href="tel:01064288020">{tel}</a>{selected ? <><h3 className="contact-form-title">이 점포, 내 업종으로 가능할까요?</h3><p className="inquiry-context-note">매물번호 {inquiryContext.reference} · 요청 내용에 자동으로 포함됩니다.</p><InquiryForm key={route} context={inquiryContext} compact onPreview={previewInquiry}/></> : <><p>업종·예산·필요한 시설부터 함께 정리합니다.</p><Button onClick={contactOpen} className="w-full">비슷한 고민 상담 요청 <ArrowRight size={16}/></Button></>}<a className="office-phone" href="tel:0313448924">사무실 031-344-8924</a></div>;

  return <>
    <div className="utility-bar"><div className="container"><span>군포·산본 상가 전문 <i/> 임대차부터 입점까지</span><div><span className="demo-notice">디자인 시안 · 가상 매물 포함</span><a href="tel:01064288020"><Phone size={12}/>{tel}</a></div></div></div>
    <header className="site-header"><div className="container header-main"><a href="#home" aria-label="선부동산 홈"><img className="logo" src={asset("/logo.svg")} alt="선부동산 LINE REAL ESTATE"/></a><form className="search-box" onSubmit={search}><Search size={20}/><input aria-label="매물 검색" placeholder="어떤 점포를 찾으세요? 업종 또는 키워드" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label="검색" type="submit"><ArrowRight size={19}/></button></form><div className="header-actions"><button onClick={()=>{setCategory("전체");setLeaseOnly(false);setMaxRent("all");setSubmittedQuery("");setShowSaved(true);window.location.hash="listings";}}><Heart size={18}/>찜한 매물 <b>{favorites.length}</b></button><Button variant="outline" onClick={contactOpen}>상담 요청</Button></div><button className="mobile-menu-button" aria-label="메뉴 열기" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button></div>
    <nav className={`main-nav ${mobileMenu?"mobile-open":""}`}><div className="container"><a className={route==="home"?"active":""} href="#home">홈</a><button className={route==="listings"&&category!=="상가 매매"?"active":""} onClick={()=>selectCategory("전체")}>상가 임대차</button><button className={category==="상가 매매"&&route==="listings"?"active":""} onClick={()=>selectCategory("상가 매매")}>상가 매매</button><a className={route==="works"||work?"active":""} href="#works">중개 완료 사례</a><a className={route==="compare"?"active":""} href="#compare">점포 비용 비교</a><a className={route==="process"?"active":""} href="#process">상담·계약 과정</a><button onClick={()=>{contactOpen();setContactGoal("내 점포 임대 의뢰");}} className="nav-tail">내 점포 내놓기 <ArrowRight size={14}/></button></div></nav></header>
    <main>
    {(route==="home"||route==="listings")&&<>
      {route==="home"&&<section className="home-intro"><div className="container hero-grid"><div className="hero-message"><span className="eyebrow">SANBON COMMERCIAL REAL ESTATE</span><h1>좋은 점포의 기준은,<br/><span>내 조건에 맞는 자리.</span></h1><p>산본의 동선과 점포의 조건을 함께 살펴봅니다.<br/>예산에 맞는 대안부터, 오픈 전 필요한 협의까지.</p><a href="#works">김영선 공인중개사의 실제 중개 이야기 <ArrowRight size={16}/></a><div className="hero-outline" aria-hidden="true"><span/><span/><span/><span/></div></div><a href="#case/cafe" className="hero-feature"><img src={asset("/images/cafe-korea.png")} alt="가상의 소형 카페 전면"/><div><span>이런 조건으로 찾고 있다면</span><h2>첫 카페, 5,000만원<br/>예산부터 비교해 보세요.</h2><span className="hero-feature-link">가상 점포 살펴보기 <ArrowRight size={16}/></span></div><span className="feature-image-note">AI 이미지 · 가상 시나리오</span></a></div></section>}
      <div className="container browse-area"><div className="industry-panel"><div className="industry-label"><Store size={20}/><strong>어떤 점포를<br/>찾으세요?</strong></div><div className="industry-options">{industries.map(({label,icon:Icon})=><button key={label} className={category===label?"selected":""} onClick={()=>{setCategory(label);setLeaseOnly(false);setShowSaved(false);}}><Icon size={25} strokeWidth={1.5}/><span>{label}</span><small>{label==="전체"?scenarios.length:scenarios.filter(s=>listingMeta[s.id].industry===label).length}개 시연</small></button>)}</div></div>
      <section className="property-section" id="properties"><div className="section-heading"><div><span className="eyebrow">FIND YOUR SPACE</span><h2>{showSaved?"찜한 매물":submittedQuery?`‘${submittedQuery}’ 검색 결과`:category==="전체"?(leaseOnly?"산본 상가 임대차 매물":"산본, 내 조건으로 찾는 점포"):`${category} 점포 살펴보기`} <span>{filtered.length}</span></h2></div><a href="#compare">비용을 먼저 비교해 보세요 <ArrowRight size={15}/></a></div>
      <div className="filter-row"><div className="filter-group"><span><MapPin size={14}/>군포시 산본동</span><span><SlidersHorizontal size={14}/>월세</span><select aria-label="월세 상한" value={maxRent} onChange={e=>setMaxRent(e.target.value)}><option value="all">전체 가격</option><option value="150">150만원 이하</option><option value="250">250만원 이하</option></select><button onClick={()=>{setCategory("전체");setLeaseOnly(false);setMaxRent("all");setQuery("");setSubmittedQuery("");setShowSaved(false);}}>초기화</button></div><small>시연용 가상 매물 · 실제 모집 아님</small></div>
      {filtered.length?<div className="listing-grid">{filtered.map(card)}</div>:<div className="empty-state"><Search size={28}/><h3>{showSaved?"아직 찜한 매물이 없어요":"조건에 맞는 시연 매물이 없습니다"}</h3><p>{showSaved?"매물 사진의 하트를 눌러 후보를 모아보세요.":"조건을 넓혀 다른 점포도 비교해 보세요."}</p><Button variant="outline" onClick={()=>{setCategory("전체");setLeaseOnly(false);setMaxRent("all");setShowSaved(false);setSubmittedQuery("");}}>전체 매물 보기</Button></div>}
      </section>
      <section className="home-inquiry" id="inquiry"><div className="home-inquiry-message"><span className="eyebrow">TELL US WHAT YOU NEED</span><h2>찾는 조건이 없나요?<br/>원하는 점포를 알려주세요.</h2><p>업종과 예산이 아직 정리되지 않아도 괜찮습니다.<br/>전화번호와 간단한 조건을 남겨주세요.</p><div className="home-inquiry-person"><span className="brand-avatar">선</span><div><strong>김영선 공인중개사가 직접 확인합니다.</strong><small>확인 후 최대한 빨리 연락드립니다.</small></div></div></div><div className="home-inquiry-inputs"><InquiryForm context={{kind:"general",goal:"상가 임대차 후보 비교"}} onPreview={previewInquiry}/></div></section>
      <section className="assistance-banner"><div className="assistance-icon"><ClipboardList size={30}/></div><div><small>마음에 드는 점포, 조건까지 맞을까요?</small><h3>보증금만 보지 말고, 오픈까지 드는 비용을 함께 보세요.</h3><p>공사·장비·운영자금까지 나란히 비교하는 가상 점포 비교표</p></div><Button asChild variant="outline"><a href="#compare">비용 비교하기 <ArrowRight size={16}/></a></Button></section>
      <section className="home-cases"><div className="section-heading"><div><span className="eyebrow">LOCAL EXPERIENCE</span><h2>계약 너머, 오픈까지 함께한 사례</h2></div><a href="#works">전체 사례 <ArrowRight size={15}/></a></div><div className="case-grid">{works.map((w,i)=><a className="case-card" key={w.id} href={`#work/${w.id}`}><div><span className="case-no">0{i+1}</span><span className="status-tag">중개 완료</span></div><small>{w.category}</small><h3>{w.name}</h3><p>{clean(w.title)}</p><div className="case-card-bottom"><span>전용 {w.area}</span><ArrowRight size={17}/></div></a>)}</div><p className="section-note">공인중개사님이 제공한 거래 당시 경험입니다. 현재 모집 중인 매물이 아니며, 실제 사진은 준비 중입니다.</p></section>
      <div className="bottom-columns"><section><div className="section-heading"><h2>점포를 보기 전에</h2><span className="text-muted">조건을 정리하는 읽을거리</span></div><div className="guide-list">{scenarios.slice(0,3).map((s,i)=><button key={s.id} onClick={()=>setGuide(s.id)}><span>0{i+1}</span><div><small>{listingMeta[s.id].industry}</small><strong>{s.guide}</strong></div><ChevronRight size={18}/></button>)}</div></section><section className="profile-panel"><span className="eyebrow">YOUR LOCAL PARTNER</span><h2>산본에서 만나는<br/>김영선 공인중개사입니다.</h2><p>조건에 맞는 점포를 찾고, 시설과 계약의 세부 조건을 함께 조율합니다.</p><div className="profile-contacts"><a href="tel:01064288020"><Phone size={16}/>{tel}</a><a href="mailto:ysyh1730@naver.com"><Mail size={16}/>ysyh1730@naver.com</a></div><Button onClick={contactOpen}>내 상황부터 이야기하기 <ArrowRight size={16}/></Button></section></div>
      </div>
    </>}

    {selected&&<div className="container detail-page"><div className="breadcrumb"><a href="#home">홈</a><ChevronRight size={12}/><a href="#listings">매물 찾기</a><ChevronRight size={12}/>{listingMeta[selected.id].industry}</div><div className="detail-title"><div><div className="detail-badges"><span className="status-tag">시연용 가상 매물</span><span>매물번호 SUN-00{selected.number}</span></div><h1>{listingMeta[selected.id].title}</h1><p><MapPin size={15}/>{selected.location}</p></div><Button variant="outline" onClick={()=>toggleFavorite(selected.id)}><Heart size={17} fill={favorites.includes(selected.id)?"currentColor":"none"}/>{favorites.includes(selected.id)?"찜 해제":"찜하기"}</Button></div>
      <div className="detail-overview"><section className="spec-panel"><div className="spec-panel-heading"><h2>매물 기본 정보</h2><span>{selected.price?"상가 매매":"상가 임대차"}</span></div><dl className="spec-table"><div className="price-row"><dt>{selected.price?"매매가":"보증금 / 월세"}</dt><dd>{selected.price?`${money(selected.price)}만원`:<>{money(selected.deposit)} <span>/</span> {money(selected.rent)}<small>만원</small></>}</dd></div><div><dt>소재지</dt><dd>군포시 산본동 <small>가상 위치</small></dd></div><div><dt>전용면적</dt><dd>{listingMeta[selected.id].area}평 <small>약 {Math.round(listingMeta[selected.id].area*3.3058)}㎡</small></dd></div><div><dt>층수</dt><dd>{listingMeta[selected.id].floor}</dd></div><div><dt>관리비</dt><dd>{selected.management}만원 / 월 <small>가정 금액</small></dd></div><div><dt>{selected.price?"임대 현황":"권리금"}</dt><dd>{selected.price?`보증금 ${money(selected.deposit)} / 월세 ${selected.rent}만원`:selected.key?`${money(selected.key)}만원`:"없음으로 가정"}</dd></div><div><dt>추천 검토 업종</dt><dd>{listingMeta[selected.id].industry}</dd></div><div><dt>입주 가능일</dt><dd>협의 전 · 미확인</dd></div></dl><p className="section-note">월세 부가세 별도. 모든 조건은 시연을 위한 가정이며 실제 매물이 아닙니다.</p><div className="spec-bottom"><a href="tel:01064288020"><Phone size={17}/>김영선 공인중개사 <b>{tel}</b></a><Button size="sm" onClick={contactOpen}>조건 상담</Button></div></section>
      <section className="gallery"><div className="gallery-main"><img src={asset(`/images/${selected.id}-korea.png`)} className={photoIndex===1?"crop-left":photoIndex===2?"crop-right":""} alt="AI로 만든 가상 점포 사진"/><span className="photo-label">AI 이미지 · 실제 점포 사진 아님</span><span className="photo-counter">{photoIndex+1} / 3 · 같은 이미지의 확대 보기</span></div><div className="gallery-thumbnails">{["전체 공간","왼쪽 확대","오른쪽 확대"].map((label,i)=><button key={label} className={photoIndex===i?"selected":""} onClick={()=>setPhotoIndex(i)} aria-label={label}><img className={i===1?"crop-left":i===2?"crop-right":""} src={asset(`/images/${selected.id}-korea.png`)} alt={label}/><span>{label}</span></button>)}</div></section></div>
      <nav className="detail-tabs">{[["intro","점포 소개"],["cost","비용·시설"],["location","입지 확인"],["checks","계약 전 확인"]].map(([id,label])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}>{label}</button>)}<button onClick={contactOpen}>상담 요청 <ArrowRight size={14}/></button></nav>
      <div className="detail-content-grid"><div><section className="detail-section" id="intro"><div className="section-heading"><h2>이런 상황이라면 함께 검토해 보세요</h2><span className="status-tag">{selected.type}</span></div><p className="intro-lead">{selected.intro}</p><div className="insight-box"><span><Sparkles size={17}/>김영선 공인중개사와 살펴볼 관점</span><p>{selected.insight}</p></div><div className="two-notes"><div><h3><Check size={16}/>검토할 장점</h3><p>{selected.positive}</p></div><div><h3><CircleHelp size={16}/>함께 확인할 제약</h3><p>{selected.caution}</p></div></div></section>
      <section className="detail-section" id="cost"><h2>비용과 시설, 같은 기준으로 비교합니다</h2><dl className="facts-grid">{selected.facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="cost-strip"><div><small>월세 + 관리비</small><strong>{selected.rent+selected.management}만원 / 월</strong></div><p>가정 금액의 단순 합계입니다.<br/>부가세·공과금·기타 운영비는 별도입니다.</p><a href="#compare">초기 비용도 비교하기 <ArrowRight size={16}/></a></div></section>
      <section className="detail-section" id="location"><h2>주소보다 중요한, 실제 고객의 동선</h2><div className="location-placeholder"><MapPin size={27}/><h3>산본 중심상가 · 가상 위치</h3><p>실제 주소와 현장 자료가 확보되면 지도와 접근 동선을 넣습니다.</p></div><p>현장에서는 간판이 보이는 방향, 고객의 이동 경로, 주차와 출입 조건을 함께 확인합니다. 가상 매물에는 실제 위치를 표시하지 않습니다.</p></section>
      <section className="detail-section" id="checks"><h2>방문·계약 전에 확인할 항목</h2><ul className="check-list">{selected.checks.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><div className="document-banner"><ClipboardList size={25}/><div><small>이 조건으로 상담하면 함께 정리할 자료</small><strong>{selected.deliverable}</strong></div><Button onClick={contactOpen}>내 조건 정리하기</Button></div></section></div><aside className="detail-sidebar">{contactCard}<div className="sidebar-note"><h3>이 페이지의 정보 기준</h3><p>시연용 가정 조건입니다. 실제 거래 시 현장·서류·견적을 확인해 조건을 정리합니다.</p><a href="#process">상담 이후 과정 보기 <ArrowRight size={14}/></a></div></aside></div><a className="back-link" href="#listings"><ArrowLeft size={16}/>매물 목록으로 돌아가기</a>
    </div>}

    {(route==="works"||work)&&<div className="container editorial-page"><div className="breadcrumb"><a href="#home">홈</a><ChevronRight size={12}/><a href="#works">중개 완료 사례</a>{work&&<><ChevronRight size={12}/>{work.name}</>}</div>{work?<><div className="editorial-heading"><span className="status-tag">실제 중개 완료 사례 · 현재 모집 아님</span><h1>{work.name}</h1><h2>{clean(work.title)}</h2><p>{work.summary}</p></div><div className="detail-content-grid"><div><div className="case-metrics"><div><small>거래 당시 보증금</small><strong>{work.deposit}</strong></div><div><small>월세 · 부가세 별도</small><strong>{work.rent}</strong></div><div><small>전용면적</small><strong>{work.area}</strong></div></div><div className="actual-photo-placeholder"><Building2 size={34}/><strong>실제 점포 사진 준비 중</strong><span>{work.address}</span></div>{work.scope&&<p className="section-note">{work.scope}</p>}{[["01","고객의 출발점",work.initial],["02","해결할 문제",work.issue],["03","협의하고 도운 일",work.actions.join(" ")],["04","오픈 이후의 관계",work.outcome]].map(([n,title,body])=><section className="detail-section" key={n}><span className="eyebrow">{n} · OUR WORK</span><h2>{title}</h2><p>{body}</p></section>)}<div className="insight-box"><span>이 사례에서 보실 수 있는 중개 방식</span><p>{work.lesson}</p></div><p className="section-note">김영선 공인중개사가 제공한 경험과 제공 당시 근황을 바탕으로 정리했습니다. 거래 연도와 사진은 추후 추가합니다.</p><div className="case-inquiry-cta"><div><h3>비슷한 고민이 있다면 상황을 남겨주세요.</h3><p>김영선 공인중개사가 확인 후 최대한 빨리 연락드립니다.</p></div><Button onClick={contactOpen}>비슷한 고민 상담 요청 <ArrowRight size={16}/></Button></div><a href="#works" className="back-link"><ArrowLeft size={16}/>다른 중개 사례 보기</a></div><aside className="detail-sidebar">{contactCard}<div className="sidebar-note"><h3>비슷한 고민이 있으신가요?</h3><ul>{work.checks.map(x=><li key={x}>{x}</li>)}</ul></div></aside></div></>:<><div className="editorial-heading"><span className="eyebrow">LOCAL EXPERIENCE</span><h1>매물을 소개하는 것에서,<br/>문제를 풀어가는 중개로.</h1><p>예산, 시설, 인수 조건, 입점 일정. 김영선 공인중개사가 직접 함께한 이야기입니다.</p></div><div className="works-list">{works.map((w,i)=><a key={w.id} href={`#work/${w.id}`}><span className="work-number">0{i+1}</span><div><span className="status-tag">{w.category}</span><h2>{w.name}</h2><h3>{clean(w.title)}</h3><p>{w.summary}</p><small>전용 {w.area} · 거래 당시 월세 {w.rent} · 부가세 별도</small></div><ArrowRight size={22}/></a>)}</div></>}</div>}

    {route==="compare"&&<div className="container editorial-page"><div className="breadcrumb"><a href="#home">홈</a><ChevronRight size={12}/>점포 비용 비교</div><div className="editorial-heading"><span className="eyebrow">COMPARE BEFORE YOU DECIDE</span><h1>같은 예산, 다른 선택.<br/>오픈까지 드는 비용을 비교하세요.</h1><p>소형 카페와 넓은 카페를 비교하는 가상 예시입니다.</p></div><div className="budget-input"><label htmlFor="budget">내 초기 예산</label><input id="budget" type="number" min="0" step="100" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)))}/><span>만원</span></div><div className="table-scroll"><table className="comparison"><thead><tr><th>비교 항목</th><th>A · 생활동선형 소형</th><th>B · 전면형 중형</th></tr></thead><tbody>{[["전용면적 / 층","13평 / 1층","18평 / 1층"],["보증금","2,000만원","3,000만원"],["월세 + 관리비","120만원","190만원"],["권리금","없음으로 가정","800만원"],["공사 / 장비","2,000 / 600만원","2,400 / 700만원"],["예비 운영자금","400만원","400만원"],["초기 예산 합계","5,000만원","7,300만원"],["운영 방향","테이크아웃 + 소수 좌석","좌석 운영 비중 높음"],["확인할 제약","좌석·창고, 실제 보행","고정비, 실제 고객 유입"]].map(([k,a,b])=><tr key={k}><th>{k}</th><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div><div className="budget-results">{[["A점포",5000],["B점포",7300]].map(([label,cost])=><div key={label} className={budget>=Number(cost)?"within":"over"}><small>{label} · 입력 예산 대비</small><strong>{money(Math.abs(budget-Number(cost)))}만원 {budget>=Number(cost)?"여유":"부족"}</strong></div>)}</div><p className="section-note">초기 합계는 보증금·권리금·공사·장비·운영자금 합계입니다. 월세·관리비·부가세·중개보수·기타 개업 비용은 미포함입니다. 모든 수치는 가정입니다.</p><Button onClick={contactOpen}>내 조건으로 비교 상담 준비 <ArrowRight size={16}/></Button></div>}

    {route==="process"&&<div className="container editorial-page"><div className="editorial-heading"><span className="eyebrow">HOW WE WORK</span><h1>연락한 다음에는,<br/>이렇게 함께 살펴봅니다.</h1><p>처음 상담부터 후보 검토, 조건 협의와 입점까지.</p></div><div className="process-list">{steps.map(([title,body,output],i)=><div key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{body}</p></div><strong><ClipboardList size={17}/>{output}</strong></div>)}</div><div className="assistance-banner"><div><h3>지금 조건이 정리되지 않았어도 괜찮습니다.</h3><p>희망 업종과 예산부터 이야기해 주세요.</p></div><Button onClick={contactOpen}>상담 준비하기 <ArrowRight size={16}/></Button></div></div>}
    {!selected&&!work&&!["home","listings","works","compare","process"].includes(route)&&<div className="container empty-state"><h1>페이지를 찾을 수 없습니다.</h1><Button asChild><a href="#home">홈으로</a></Button></div>}
    </main>
    <div className="mobile-inquiry-bar"><a href="tel:01064288020" aria-label="김영선 공인중개사에게 전화하기"><Phone size={18}/><span>전화</span></a><Button onClick={contactOpen}>{selected ? "이 매물 상담 요청" : "내 조건으로 문의하기"}<ArrowRight size={16}/></Button></div>
    <aside className="floating-tools"><button onClick={()=>{setShowSaved(true);setCategory("전체");setLeaseOnly(false);setMaxRent("all");setSubmittedQuery("");window.location.hash="listings";}}><Heart size={18}/><span>찜한 매물</span><b>{favorites.length}</b></button><div className="recent-tools"><small>최근 본 매물</small>{recent.length?recent.map(id=><a key={id} href={`#case/${id}`}><img src={asset(`/images/${id}-korea.png`)} alt={listingMeta[id]?.title}/></a>):<span className="recent-empty">매물을<br/>살펴보세요</span>}</div><button onClick={contactOpen}><Phone size={18}/><span>상담 요청</span></button><button aria-label="맨 위로" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><ChevronUp size={18}/><span>TOP</span></button></aside>
    <footer><div className="container footer-top"><img src={asset("/logo.svg")} alt="선부동산"/><div><strong>산본의 자리와 사람을 연결합니다.</strong><span>상가 임대차 · 상가 매매 · 입점 조건 협의</span></div><a href="tel:01064288020">{tel}<Phone size={18}/></a></div><div className="container footer-bottom"><p>선 공인중개사 · 공인중개사 김영선<br/>경기도 군포시 산본로 323번길 16-15 (산본동 1135) 광림프라자 208호<br/>사무실 031-344-8924 · 이메일 ysyh1730@naver.com</p><p>DESIGN PREVIEW · 2026<br/>가상 매물은 실제로 모집 중인 매물이 아닙니다.<br/>실제 중개 사례의 금액은 거래 당시 조건입니다.</p></div></footer>
    <Dialog open={contact} onOpenChange={setContact}><DialogContent><DialogTitle className="text-2xl font-bold">{draft ? "상담 요청 내용 미리보기" : contactGoal === "내 점포 임대 의뢰" ? "내 점포의 임대 조건을 알려주세요" : selected ? "이 매물에 대해 문의하세요" : work ? "비슷한 고민을 알려주세요" : "내 조건에 맞는 점포를 요청하세요"}</DialogTitle><DialogDescription className="mt-2 text-sm text-neutral-500">{draft ? "현재는 시안으로, 아래 내용은 실제로 접수되지 않았습니다." : "김영선 공인중개사가 확인 후 최대한 빨리 연락드립니다."}{modalInquiryContext.title && !draft && <><br/>{modalInquiryContext.title}{modalInquiryContext.reference && ` · ${modalInquiryContext.reference}`}</>}</DialogDescription>{!draft ? <InquiryForm key={`${route}-${contactGoal}`} context={modalInquiryContext} onPreview={previewInquiry}/> : <div className="draft-preview"><pre>{draft}</pre><Button onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setCopied(false);}}}>{copied ? <Check size={16}/> : <ClipboardList size={16}/>} {copied ? "복사했습니다" : "상담 내용 복사"}</Button><Button asChild variant="outline"><a href={`mailto:ysyh1730@naver.com?subject=${encodeURIComponent("산본 상가 상담 문의")}&body=${encodeURIComponent(draft)}`}><Mail size={16}/>이메일 앱 열기</a></Button><a className="contact-phone" href="tel:01064288020">전화로 이야기하기 · {tel}</a><p className="section-note">아직 접수되지 않았습니다. 복사한 내용을 직접 전달하거나 이메일 앱에서 전송해 주세요.</p></div>}</DialogContent></Dialog>
    <Dialog open={!!guide} onOpenChange={open=>{if(!open)setGuide(null);}}><DialogContent><DialogTitle className="pr-5 text-xl font-bold">{scenarios.find(s=>s.id===guide)?.guide}</DialogTitle><DialogDescription className="mt-4 leading-7 text-neutral-600">{scenarios.find(s=>s.id===guide)?.guideBody}</DialogDescription><Button asChild className="mt-6"><a href={`#case/${guide}`} onClick={()=>setGuide(null)}>관련 가상 점포 보기 <ArrowRight size={16}/></a></Button></DialogContent></Dialog>
  </>;
}
